### PR TITLE
lancelot-Spark-Rom-pyro-deadaf5

### PR DESCRIPTION
**Pull request by deadaf5**

### CODE REVIEW

**Comment by baconpeedit** [comment]
Don't Rerun Builds

**Comment by deadaf5** [comment]
> Don't Rerun Builds

Sir new build is added gapps kernel tweaks and sound fix

**Comment by baconpeedit** [comment]
All i saw that is one build you did rerun and one you triggered with a new pr (which means you triggered 2 builds at a same time)

1. Reruning builds are not allowed
2. Pushing 2 builds simultaneously not allowed

If i ever again found you doing this will abort your builds and have to get you permanently blocked from @ROM-builders

**Comment by deadaf5** [comment]
> All i saw that is one build you did rerun and one you triggered with a new pr (which means you triggered 2 builds at a same time)
> 
> 1. Reruning builds are not allowed
> 2. Pushing 2 builds simultaneously not allowed
> 
> If i ever again found you doing this will abort your builds and have to get you permanently blocked from @ROM-builders 

Sorry sir I will keep in mind

**Pull request closed without merging**
