### PR TITLE
los  test

### PR DESCRIPTION
**Pull request by AkhilmsAchu**

### CODE REVIEW

**Comment by Apon77** [comment]
How git reset hard will help here?

**Comment by AkhilmsAchu** [comment]
> How git reset hard will help here?

While sync, it will throw some error due to un committed changes in the directory. I don't know how those changes are made. It happens every time i tried to sync havoc source. That's why i was using git reset hard

**Comment by Apon77** [comment]
> > How git reset hard will help here?
> 
> While sync, it will throw some error due to un committed changes in the directory. I don't know how those changes are made. It happens every time i tried to sync havoc source. That's why i was using git reset hard

Link of that error?

**Comment by AkhilmsAchu** [comment]
> > > How git reset hard will help here?
> > 
> > 
> > While sync, it will throw some error due to un committed changes in the directory. I don't know how those changes are made. It happens every time i tried to sync havoc source. That's why i was using git reset hard
> 
> Link of that error?

Part of error. It was a week ago. So i can't find those logs. Pasting this from my google search history.

error: Unable to fully sync the tree.error: Checking out local projects failed.

**Pull request closed without merging**
