### PR TITLE
pine-Awaken-iaiaian1 include anxcamera and props

### PR DESCRIPTION
**Pull request by iaiaian1**

### CODE REVIEW

**Comment by rasenss** [comment]
You just sucessed build syberia
And now you build another Rom
Oh damn buildbot
People like you makes server overhelmed

**Comment by iaiaian1** [comment]
I keep my build maximum to 3. That was my first build here.

**Comment by rasenss** [comment]
No no 
I mean why you didnt test your finished build first

**Comment by iaiaian1** [comment]
I actually did test the syberia.

**Pull request closed without merging**
