### PR TITLE
beryllium-PixelExperience-twelve-plus-RadeonPS

### PR DESCRIPTION
**Pull request by RadeonPS**
Correcting PR label

### CODE REVIEW

**Comment by NRanjan-17** [comment]
Use https://github.com/PixelExperience/manifest.git

**Comment by RadeonPS** [comment]
Changed incorrect repo link to https://github.com/PixelExperience/manifest.git

**Comment by RadeonPS** [comment]
[build3.log.txt](https://github.com/ROM-builders/temporary/files/10253646/build3.log.txt)
error log

**Comment by RadeonPS** [comment]
Moving to forked RadeonPS/device_xiaomi_beryllium1

**Comment by RadeonPS** [comment]
PEA11 branch unsupported in cirrus

**Pull request closed without merging**
