### PR TITLE
pissarro-LineageOS-lineage-19.1-Kartik-91

### PR DESCRIPTION
**Pull request by Kartik-91**

### CODE REVIEW

**Comment by angreno** [comment]
Heyy buddy are u trying to develop rom for pissarro?

**Comment by Kartik-91** [comment]
> Heyy buddy are u trying to develop rom for pissarro?

Yes, we already booted it but have some problem with display

**Comment by angreno** [comment]
> > Heyy buddy are u trying to develop rom for pissarro?
> 
> Yes, we already booted it but have some problem with display 

So glad can't wait to try it ,can i get your insta?

**Comment by Kartik-91** [comment]
> > > Heyy buddy are u trying to develop rom for pissarro?
> > 
> > 
> > Yes, we already booted it but have some problem with display
> 
> So glad can't wait to try it ,can i get your insta?

U can contact me on Telegram https://t.me/Kartik11i

**Pull request closed without merging**
