### PR TITLE
Fix sync [skip ci]

### PR DESCRIPTION
**Pull request by P-Salik**

### CODE REVIEW

**Comment by Apon77** [comment]
Is this really needed? Did you test with any sync?

**Review by Apon77 — COMMENTED** [review]
Is this really needed? Did you test with any sync?

**Comment by P-Salik** [comment]
Can't test cuz cirrus gives error (for building aosp blah)

**Comment by P-Salik** [comment]
> Is this really needed? Did you test with any sync?

Can u plox check tg pm

**Comment by P-Salik** [comment]
If sync fails the script doesn't remove .repo/projects/<failed repo>.git

I processed my sync.log with ur script and it removes .repo/project-objects/<failed repo>.git (android_bionic in my case)

https://github.com/ROM-builders/temporary/blob/9536d79bf8fd963582e5993ab999b944476fe57e/.cirrus.yml#L99

This statement removes  .repo/project-objects/*bionic.git (which nukes android_bionic)

But in .repo/projects/ it nukes .repo/projects/bionic.git which doesn't exist (android_bionic exists which it shd remove)

https://github.com/ROM-builders/temporary/blob/9536d79bf8fd963582e5993ab999b944476fe57e/.cirrus.yml#L128

After that, this statement removes  .repo/project-objects/android_bionic.git only but doesn't remove .repo/projects/android_bionic.git

**Pull request closed without merging**
