### PR TITLE
Some more changes to the build script

### PR DESCRIPTION
**Pull request by LinkBoi00**
- Switch to user builds
- mka clean to delete /out

### CODE REVIEW

**Review by Apon77 — COMMENTED** [review]
No need clean for now, let's build dirty, and check if it's fine or not, AFAIK android is smart enough to do dirty build

**Comment by LinkBoi00** [comment]
Nope, I have bugs with dirty build

**Comment by LinkBoi00** [comment]
It doesn't rebuild the display hals

**Review by Apon77 — COMMENTED** [review]
Let's not make clean and check if it's fine, we have queues to fill.

**Comment by LinkBoi00** [comment]
Please merge this for now, I'll delete mka clean soon (I just need one or two clean builds)

**Pull request closed without merging**
